# Generated by Django 2.2.24 on 2021-07-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgae',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='イメージ画像'),
        ),
    ]
