# Generated by Django 2.2.24 on 2021-07-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgae',
            new_name='image',
        ),
    ]
